import Head from 'next/head'
import Header from '../../components/Header'
import Navbar from '../../components/Navbar'
import requests from '../../utils/requests'
import Results from '../../components/Results'

interface ResultObj {
  adult: boolean,
  backdrop_path: string,
  genre_ids: number[],
  id: number,
  media_type: string,
  original_language: string,
  original_title: string,
  overview: string,
  popularity: number,
  poster_path: string,
  release_date: string,
  title: string,
  video: boolean,
  vote_average: number,
  vote_count: number
}

type MyProps = {
  results: ResultObj[]
}

  const Home: React.FC<MyProps> = ({ results }) => {
  return (
    <>
      <Head>
        <title>IMDB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Navbar />
        <Results results={results} />
      </main>
    </>
  )
}

export default Home

export async function getServerSideProps(context: any) {
  const genre = context.query.genre || "fetchTrending"
  const request = await fetch(`
  https://api.themoviedb.org/3${requests[genre].url}
  `)
  .then(response => response.json())

  return{
    props:{
      results: request.results,
    }
  }
}